// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DiUfqrHAVlpT9eQYjcL0P2ikR9vbfmE',
    appId: '1:173322487200:web:e92be4625c2b39275710c5',
    messagingSenderId: '173322487200',
    projectId: 'microlab-412c7',
    authDomain: 'microlab-412c7.firebaseapp.com',
    storageBucket: 'microlab-412c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWIhzluBCUBbyPSnkYoqY_YsvUsrDp5Ok',
    appId: '1:173322487200:android:e0f051a576fc44ee5710c5',
    messagingSenderId: '173322487200',
    projectId: 'microlab-412c7',
    storageBucket: 'microlab-412c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0IpBzxsU6-UjVBu0qwej0Jc50yNUQyg0',
    appId: '1:173322487200:ios:59c148de727e4ca45710c5',
    messagingSenderId: '173322487200',
    projectId: 'microlab-412c7',
    storageBucket: 'microlab-412c7.appspot.com',
    iosClientId: '173322487200-1d1ruvmap3r4gv11n5qgnqlp05jfdk1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.microlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0IpBzxsU6-UjVBu0qwej0Jc50yNUQyg0',
    appId: '1:173322487200:ios:59c148de727e4ca45710c5',
    messagingSenderId: '173322487200',
    projectId: 'microlab-412c7',
    storageBucket: 'microlab-412c7.appspot.com',
    iosClientId: '173322487200-1d1ruvmap3r4gv11n5qgnqlp05jfdk1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.microlab',
  );
}
